Repository odyssey-dev/Odyssey, pull requests merged in 2020-12, with the labels that each got.

#198 194 Switch to using district stack as default badge page as this will be the only badge available in beta build 0.1
  src/components/app-pages/badge-pages/badge-single-template.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/toolbar/toolbar.svelte
Labels: App Structure

#200 197 Make single badge page
  src/components/app-pages/badge-pages/badge-sngl.svelte
Labels: Feature

#201 Added functionality to show/hide to stack page
  src/components/app-pages/badge-pages/badge-sngl.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/static/svgs/previous.svg
Labels: Feature

#205 settings fix
  src/components/app-pages/settings.svelte
  src/components/bottom-card/recent.svelte
Labels: Feature

#206 Develop 0.0.9
  package-lock.json
  package.json
  src/components/app-pages/badge-pages/badge-single-template.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/settings.svelte
  src/components/bottom-card/recent.svelte
  src/components/toolbar/toolbar.svelte
  src/static/svgs/previous.svg
Labels: Release

#237 Hackathon2
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/current-location-card.svelte
  src/components/profile.svelte
  src/static/svgs/flags/gb-eng.svg
  src/static/svgs/flags/gb-ni.svg
  src/static/svgs/flags/gb-sct.svg
  src/static/svgs/flags/gb-wls.svg
  src/static/svgs/flags/gb.svg
Labels: Hackathon

#236 Hackathon
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/profile.svelte
  src/components/bottom-card/recent.svelte
Labels: Feature

#225 224 MODAL: Make modal look better
  src/components/modal/achievement-get.svelte
  src/components/modal/modal.svelte
Labels: Graphic

#238 Hackathon
  src/components/app-pages/settings.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/js/locationIntro.js
  src/js/notificationsIntro.js
Labels: Hackathon

#239 Hackathon 2
  src/components/landing-page/main.svelte
  src/components/landing-page/slide-1.svelte
  src/components/landing-page/slide-2.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/components/landing-page/slide-5.svelte
  src/components/profile.svelte
Labels: Hackathon

#240 Alpha 0.0.10
  cordova/package-lock.json
  cordova/package.json
  package-lock.json
  package.json
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/landing-page/main.svelte
  src/components/landing-page/slide-1.svelte
  src/components/landing-page/slide-2.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/components/landing-page/slide-5.svelte
  src/components/modal/achievement-get.svelte
  src/components/modal/modal.svelte
  src/components/profile.svelte
  src/js/locationIntro.js
  src/js/notificationsIntro.js
  src/static/svgs/flags/gb-eng.svg
  src/static/svgs/flags/gb-ni.svg
  src/static/svgs/flags/gb-sct.svg
  src/static/svgs/flags/gb-wls.svg
  src/static/svgs/flags/gb.svg
Labels: Release
