Repository odyssey-dev/Odyssey, pull requests merged in 2020-11, with the labels that each got.

#113 Moved achievement-get functionality into component
  src/components/achievement-get.svelte
  src/components/modal/achievement-get.svelte
  src/components/modal/modal.svelte
  src/pages/home.svelte
Labels: Maintenance

#115 fixed long/lat flag styling
  src/components/current-location-card.svelte
  src/static/svgs/location.svg
Labels: Bug

#116 Separated Out Intro Cards
  src/components/landing-page/main.svelte
  src/components/landing-page/slide-1.svelte
  src/components/landing-page/slide-2.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/components/landing-page/slide-5.svelte
  src/components/landing.svelte
  src/pages/home.svelte
Labels: Feature

#119 Make current-location hide when top-profile shown
  src/components/current-location-card.svelte
  src/pages/home.svelte
Labels: Feature

#118 Feature/dev tools status#101
  src/components/app.svelte
  src/components/devtools.svelte
  src/components/top-profile/prof-settings.svelte
  src/components/top-profile/profile.svelte
  src/pages/home.svelte
Labels: Feature

#120 Feature/show badges in app#86
  src/components/listBadges.svelte
  src/pages/home.svelte
Labels: Feature

#121 Develop
  src/components/achievement-get.svelte
  src/components/app.svelte
  src/components/bottom-card/main.svelte
  src/components/bottom-card/monthly.svelte
  src/components/bottom-card/pinned.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/devtools.svelte
  src/components/landing-page/main.svelte
  src/components/landing-page/slide-1.svelte
  src/components/landing-page/slide-2.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/components/landing-page/slide-5.svelte
  src/components/landing.svelte
  src/components/listBadges.svelte
  src/components/modal/achievement-get.svelte
  src/components/modal/modal.svelte
  src/components/top-profile/prof-badges.svelte
  src/components/top-profile/prof-settings.svelte
  src/components/top-profile/profile.svelte
  src/pages/home.svelte
  src/static/svgs/location.svg
  src/static/svgs/no-selected-badge.svg
Labels: Release

#122 min height and longitude, latitude fix
  src/js/geolocation.js
  src/pages/home.svelte
Labels: Bug

#128 124 Adjust styling and move current-location to bottom-card
  src/components/bottom-card/main.svelte
  src/components/bottom-card/monthly.svelte
  src/components/bottom-card/pinned.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/pages/home.svelte
Labels: Feature

#132 implementing bottom nav
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
  src/components/full-screen-el/prof-badges.svelte
  src/components/full-screen-el/prof-settings.svelte
  src/components/full-screen-el/profile.svelte
  src/components/toolbar/toolbar.svelte
  src/pages/home.svelte
Labels: Feature

#135 133 Change Icons on Bottom Nav
  src/components/toolbar/toolbar.svelte
Labels: Feature

#138 Feature/pwa
  build/webpack.config.js
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/lastUpdated.svelte
  src/index.html
  src/js/LastUpdated.js
  src/js/firebase.js
  src/js/geolocation.js
  src/js/networkCheck.js
  src/js/profile.js
  src/js/store.js
  src/js/userstate.js
  src/manifest.json
  src/pages/home.svelte
  src/service-worker.js
Labels: Feature

#139 0.0.5
  build/webpack.config.js
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
  src/components/bottom-card/main.svelte
  src/components/bottom-card/monthly.svelte
  src/components/bottom-card/pinned.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/full-screen-el/prof-badges.svelte
  src/components/full-screen-el/prof-settings.svelte
  src/components/full-screen-el/profile.svelte
  src/components/lastUpdated.svelte
  src/components/toolbar/toolbar.svelte
  src/index.html
  src/js/LastUpdated.js
  src/js/firebase.js
  src/js/geolocation.js
  src/js/networkCheck.js
  src/js/profile.js
  src/js/store.js
  src/js/userstate.js
  src/manifest.json
  src/pages/home.svelte
  src/service-worker.js
Labels: Feature

#142 0.0.5
  package-lock.json
  package.json
Labels: Feature

#149 146 Icon
  assets-src/cordova-android-icon.png
  assets-src/cordova-ios-icon.png
  assets-src/cordova-splash-screen.png
  src/index.html
Labels: Feature, Graphic

#150 147 Begin Implementation of Profile Page
  package-lock.json
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
Labels: Feature

#158 151 Begin Implementation of Badge Pages
  src/components/app-pages/badge-pages/badge-menu.svelte
  src/components/app-pages/badge-pages/display-badge.svelte
  src/components/app-pages/badges.svelte
Labels: Feature

#157 147 Begin Implementation of Profile Page
  src/components/app-pages/profile.svelte
Labels: Feature

#164 146 Icon
  src/manifest.json
  src/static/logo-variations/cordova-android-icon.png
  src/static/logo-variations/cordova-ios-icon.png
  src/static/logo-variations/cordova-splash-screen.png
  static/icons/128x128.png
  static/icons/144x144.png
  static/icons/152x152.png
  static/icons/192x192.png
  static/icons/256x256.png
  static/icons/512x512.png
Labels: Feature

#165 moved home.svelte "top-component" to profile.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Maintenance

#166 151 Begin Implementation of Badge Pages
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
Labels: Maintenance

#167 137 Show Achievement Popup on Achievement
  src/components/modal/achievement-get.svelte
  src/js/geolocation.js
  src/pages/home.svelte
Labels: Feature

#176 174 Add show more to badge cards on main badge page
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
Labels: Feature

#178 153 settings config
  src/components/app-pages/settings.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/devtools.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/js/geolocation.js
  src/js/profile.js
  src/js/store.js
  src/js/userstate.js
Labels: Feature

#181 Release 0.0.7
  src/components/app-pages/badge-pages/badge-menu.svelte
  src/components/app-pages/badge-pages/badge-single-template.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/badge-pages/display-badge.svelte
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/components/devtools.svelte
  src/components/landing-page/slide-3.svelte
  src/components/landing-page/slide-4.svelte
  src/components/profile.svelte
  src/js/geolocation.js
  src/js/profile.js
  src/js/store.js
  src/js/userstate.js
Labels: Release

#183 182 Settings Page Hotfix
  src/components/app-pages/settings.svelte
Labels: Bug

#187 179 reduce repetition in code by making the card framework its own component with a <slot /> within ALL sub-pages
  src/components/app-pages/app-pages.svelte
  src/components/app-pages/badge-pages/badge-single-template.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
Labels: Maintenance

#189 0.0.8
  src/components/app-pages/app-pages.svelte
  src/components/app-pages/badge-pages/badge-single-template.svelte
  src/components/app-pages/badge-pages/badge-stack-template.svelte
  src/components/app-pages/badges.svelte
  src/components/app-pages/profile.svelte
  src/components/app-pages/settings.svelte
  src/components/bottom-card/monthly.svelte
Labels: Release

#190 var profileSettings = JSON.parse(profileStore);
  src/components/app-pages/settings.svelte
Labels: Bug
