Repository odyssey-dev/Odyssey, pull requests merged in 2020-10, with the labels that each got.

#45 Logo Variations Added to Repo
  src/static/logo-variations/black-icon-color-standard.svg
  src/static/logo-variations/black-icon.svg
  src/static/logo-variations/black-trans-bg.png
  src/static/logo-variations/color-icon.svg
  src/static/logo-variations/color-trans-bg.png
  src/static/logo-variations/logo-black-color-bg.jpg
  src/static/logo-variations/logo-color-white-bg.jpg
  src/static/logo-variations/logo-white-color-bg.jpg
  src/static/logo-variations/white-icon-color-standard.svg
  src/static/logo-variations/white-icon.svg
  src/static/logo-variations/white-trans-bg.png
Labels: Graphic

#46 Greatly improved intro cards
  src/components/landing.svelte
  src/components/login.svelte
  src/pages/home.svelte
  src/static/intro-cards/img-1.jpg
  src/static/intro-cards/img-2.jpg
  src/static/intro-cards/img-3.jpg
  src/static/intro-cards/img-4.jpg
  src/static/intro-cards/img-5.jpg
Labels: Feature

#57 Homepage styling changes
  src/pages/home.svelte
Labels: Maintenance

#58 #51: firebase setup
  .firebaserc
  firebase-hosting-pull-request.yml
  firebase.json
  package.json
  src/js/firebase.js
  src/pages/home.svelte
Labels: Maintenance

#64 Created achievement-get & modal .svelte
  src/components/achievement-get.svelte
  src/components/modal.svelte
  src/pages/home.svelte
  src/static/badge/sample-badge.svg
Labels: Feature

#66 Removed unused pages and their references in routes.js
  src/js/routes.js
  src/pages/about.svelte
  src/pages/dynamic-route.svelte
  src/pages/form.svelte
  src/pages/product.svelte
  src/pages/profile.svelte
  src/pages/request-and-load.svelte
  src/pages/settings.svelte
Labels: Maintenance

#67 Feature/api update
  src/js/api.js
  src/js/firebase.js
  src/pages/home.svelte
Labels: Feature

#69 added bare-bones profile to home.svelte
  src/components/achievement-get.svelte
  src/components/prof-badges.svelte
  src/components/prof-settings.svelte
  src/components/prof-stats.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Feature

#70 Fixing homepage
  src/pages/home.svelte
Labels: Bug

#71 achievement-get popup works & styling fixes
  src/components/achievement-get.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Feature

#73 call api
  src/pages/home.svelte
Labels: Feature

#63 Develop
  .firebaserc
  .gitignore
  firebase.json
  package.json
  src/components/achievement-get.svelte
  src/components/modal.svelte
  src/components/prof-badges.svelte
  src/components/prof-settings.svelte
  src/components/prof-stats.svelte
  src/components/profile.svelte
  src/js/api.js
  src/js/firebase.js
  src/js/routes.js
  src/pages/about.svelte
  src/pages/dynamic-route.svelte
  src/pages/form.svelte
  src/pages/home.svelte
  src/pages/product.svelte
  src/pages/profile.svelte
  src/pages/request-and-load.svelte
  src/pages/settings.svelte
  src/static/badge/sample-badge.svg
Labels: Feature

#87 Settings page created
  src/components/logout.svelte
  src/components/prof-settings.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Feature

#90 Feature/devtools
  src/components/app.svelte
  src/components/devtools.svelte
  src/js/api.js
  src/js/firebase.js
  src/pages/home.svelte
Labels: Feature

#92 Location component
  src/components/current-location-card.svelte
  src/components/listBadges.svelte
  src/js/firebase.js
  src/js/geolocation.js
  src/js/store.js
  src/pages/home.svelte
Labels: Maintenance

#91 Add sound to achievement
  src/components/prof-badges.svelte
  src/components/prof-stats.svelte
  src/components/profile.svelte
  src/pages/home.svelte
  src/static/audio/app_alert_tone_011.mp3
  src/static/audio/app_alert_tone_012.mp3
  src/static/audio/app_alert_tone_013.mp3
Labels: Feature

#93 Show Badge
  .github/workflows/github.yml
  README.md
  src/components/listBadges.svelte
  src/js/firebase.js
  src/pages/home.svelte
Labels: Feature

#94 0.0.3
  src/components/app.svelte
  src/components/current-location-card.svelte
  src/components/devtools.svelte
  src/components/listBadges.svelte
  src/components/logout.svelte
  src/components/prof-badges.svelte
  src/components/prof-settings.svelte
  src/components/prof-stats.svelte
  src/components/profile.svelte
  src/js/api.js
  src/js/firebase.js
  src/js/geolocation.js
  src/js/store.js
  src/pages/home.svelte
  src/static/audio/app_alert_tone_011.mp3
  src/static/audio/app_alert_tone_012.mp3
  src/static/audio/app_alert_tone_013.mp3
Labels: Feature

#95 Profile swiper fix
  src/components/prof-settings.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Bug

#96 Added 'svelte/slide' animation to top-card
  src/components/prof-settings.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Feature

#97 Develop
  src/components/prof-settings.svelte
  src/components/profile.svelte
  src/pages/home.svelte
Labels: Feature

#106 loc card
  src/components/current-location-card.svelte
  src/js/geolocation.js
Labels: Feature

#107 Develop
  src/components/current-location-card.svelte
  src/js/geolocation.js
Labels: Feature

#108 Location on click
  src/components/current-location-card.svelte
  src/pages/home.svelte
Labels: Bug

#112 Created bottom card element
  src/components/bottom-card/main.svelte
  src/components/bottom-card/monthly.svelte
  src/components/bottom-card/pinned.svelte
  src/components/bottom-card/recent.svelte
  src/components/current-location-card.svelte
  src/pages/home.svelte
  src/static/svgs/no-selected-badge.svg
Labels: Feature
